#pragma once

#include "driver/gpio.h"

#define SD_CS_GPIO GPIO_NUM_18
#define SD_MOSI_GPIO GPIO_NUM_17
#define SD_MISO_GPIO GPIO_NUM_16
#define SD_CLK_GPIO GPIO_NUM_15

#define MOTOR_PWMB_GPIO GPIO_NUM_13
#define MOTOR_BIN2_GPIO GPIO_NUM_12
#define MOTOR_BIN1_GPIO GPIO_NUM_11
#define MOTOR_STBY_GPIO GPIO_NUM_10
#define MOTOR_AIN1_GPIO GPIO_NUM_9
#define MOTOR_AIN2_GPIO GPIO_NUM_6
#define MOTOR_PWMA_GPIO GPIO_NUM_5